[[redirects]]
  from = "https://backup4.chatchaos.tv/*"
  to = "https://jd-hughes.github.io/chatchaos/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "https://backup.chatchaos.tv/*"
  to = "https://jd-hughes.github.io/chatchaos/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}