[[redirects]]
  from = "https://backup.chatchaos.tv/*"
  to = "https://jd-hughes.github.io/chatchaos/:splat"
  status = 200
  force = true # COMMENT: ensure that we always redirect
  headers = {X-From = "Netlify"}